# Indexing and Slicing

## 1-D Array Indexing

In [11]:
import numpy as np

arr1D = np.array([100, 200, 300, 400, 500, 600, 700])

# Positive Indexing
print(arr1D[2]) # 300
print(arr1D[6]) # 700
print(arr1D[0]) # 100
print(arr1D[4]) # 500

# Negative Indexing
print(arr1D[-1]) # 700
print(arr1D[-4]) # 400
print(arr1D[-7]) # 100
print(arr1D[-5]) # 300

300
700
100
500
700
400
100
300


## 1-D array Slicing

In [ ]:
arr1 = np.array([100, 200, 300, 400, 500, 600, 700])

# Positive Slicing
print(arr1[0:5]) # 100, 200, 300, 400, 500
print(arr1[2:6]) # 300, 400, 500, 600
print(arr1[3:5]) #  400, 500,

# Stop Only
print(arr1[:5]) # 100, 200, 300, 400, 500
print(arr1[:7]) # 100, 200, 300, 400, 500, 600, 700
print(arr1[:]) # 100, 200, 300, 400, 500, 600, 700


# Negative Slicing
print(arr1[:-5:-1]) # Stop at -5 and move by -1 (Reverse Indexing)
print(arr1[::-1]) # 700 600 500 400 300 200 100
print(arr1[::-2]) # Step by 2 [700 500 300 100]

# Last 3 Elements
print(arr1[-3:]) # 500, 600, 700

# Last 4 Elements
print(arr1[-4:]) # 400, 500, 600, 700]

# Start at 200 and Stop 500
print(arr1[-6:-2]) 

# Start at 500 and 600
print(arr1[-3:-1])


# Reversing the Array

# Print the Array in Decenting Order
print(arr1[::-1]) # [700 600 500 400 300 200 100]

# Skip a Value at each iteration
print(arr1[::-2]) # [700 500 300 100]


[100 200 300 400 500]
[300 400 500 600]
[400 500]
[100 200 300 400 500]
[100 200 300 400 500 600 700]
[100 200 300 400 500 600 700]
[700 600 500 400]
[700 600 500 400 300 200 100]
[700 500 300 100]
[500 600 700]
[400 500 600 700]
[200 300 400 500]
[500 600]
[700 600 500 400 300 200 100]
[700 500 300 100]


## 2-D array Indexing

In [7]:
import numpy as np

arr2D = np.array([
    # Column
    # 0  1  2
    [10,20,30], # 0   Row
    [40,50,60], # 1
    [70,80,90]  # 2
])

# Print number 50
print(arr2D[1,1])

# Print number 80
print(arr2D[2,1])

# Print number 60
print(arr2D[1,2])

# Print number 20
print(arr2D[0,1])

# Print number 40
print(arr2D[1,0])

50
80
60
20
40


## 2-D array Slicing

In [4]:
import numpy as np

arrD2 = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
]) 

# Extract the first two rows.
print(arrD2[0:2,:])

# Extract the last two columns.
print(arrD2[:,2:])

# Extract the following sub-array: 
# [[60 70]
# [100 110]]
print(arrD2[1:,1:3])

# Extract the second row only.
print(arrD2[1:2])

# Extract the following sub-array:
# [[20 30]
# [60 70]
# [100 110]]
print(arrD2[:,1:3])

# Extract the following sub-array
# [[20 30 40]
# [60 70 80]]
print(arrD2[0:2, 1:])

# Extract the following sub-array
# [[50 60 70 80]
# [90 100 110 120]]
print(arrD2[1:])

# Extract the following sub-array
# [[40]
# [80]
# [120]]
print(arrD2[:,3 : ])

# Extract the following sub-array
# [[20 40]
# [100 120]]
print(arrD2[0::2, 1::2 ])




[[10 20 30 40]
 [50 60 70 80]]
[[ 30  40]
 [ 70  80]
 [110 120]]
[[ 60  70]
 [100 110]]
[[50 60 70 80]]
[[ 20  30]
 [ 60  70]
 [100 110]]
[[20 30 40]
 [60 70 80]]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[[ 40]
 [ 80]
 [120]]
[[ 20  40]
 [100 120]]


### Negative Indexing and Slicing

In [23]:

# Row

# Extracting the last row of an array using (-)Negative Indexes
print(arrD2[-1]) # -1 indexes the last row of the array

# Extract the Row 1 using Negative Index
print(arrD2[-2])

# Extract the Row 0 
print(arrD2[-3])

# Column

# Row 3
print(arrD2[:, -1: ])

# Row 2
print(arrD2[:, -2::2])

# Extrtact Last Two Rows
print(arrD2[-2: ])

# Last Column
print(arrD2[:,-1])

# Last Two Columns
print(arrD2[:, -2: ])

# Reverse the Rows
print(arrD2[::-1])

# Reverse the Columns
print(arrD2[:, ::-1])

# Reverse Both Rows and Columns
print(arrD2[::-1, ::-1])

# Every Second Column in Reverse
print(arrD2[:, ::-2])

[ 90 100 110 120]
[50 60 70 80]
[10 20 30 40]
[[ 40]
 [ 80]
 [120]]
[[ 30]
 [ 70]
 [110]]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[ 40  80 120]
[[ 30  40]
 [ 70  80]
 [110 120]]
[[ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]
[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]]
[[120 110 100  90]
 [ 80  70  60  50]
 [ 40  30  20  10]]
[[ 40  20]
 [ 80  60]
 [120 100]]


#### More Questions

In [41]:
# Extract the folllowing sub-Array
# [[ 70  80]
# [110 120]]

print(arrD2[-2:, -2:])

# Extract the folllowing sub-Array
# [[120 110 100  90]
# [ 80  70  60  50]]
print(arrD2[-1:-3:-1, ::-1])

# Extract the folllowing sub-Array
# [[120 100]
# [ 80  60]
# [ 40  20]]
print(arrD2[::-1, ::-2])

# Extract the folllowing sub-Array
# [[110 120]
# [ 70  80]
# [ 30  40]]
print(arrD2[::-1, 2:])

# Extract the folllowing sub-Array
# [[120  80  40]]
print(arrD2[:,:-2:-1])

# Extract the folllowing sub-Array
# [[110  90]
# [ 70  50]
# [ 30  10]]
print(arrD2[::-1, -2::-2])

[[ 70  80]
 [110 120]]
[[120 110 100  90]
 [ 80  70  60  50]]
[[120 100]
 [ 80  60]
 [ 40  20]]
[[110 120]
 [ 70  80]
 [ 30  40]]
[[ 40]
 [ 80]
 [120]]
[[110  90]
 [ 70  50]
 [ 30  10]]


##### Recap (Revision)

In [26]:
import numpy as np

# Revision of Indexing and Slicing on 1-D Array
arr1D = np.array([10,20,30,40,50,60])

# print all the element
print(arr1D[:])

# print element 40 
print(arr1D[3])

# print all the element in reverse order
print(arr1D[::-1])

# Use Negative indexing to print element 20
print(arr1D[-5])

# print last 4 elements
print(arr1D[-4:])

# print element 40 30 20
print(arr1D[-3:-6:-1])

# print element 30 20 10
print(arr1D[-4::-1])

# print element 40 50 60
print(arr1D[-3:])

# print first 4 elements
print(arr1D[-6:-2:1])


# 2-D array Indexing Revision

arr2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90],
    [100,110,120]
])


# print elemenst 110
print(arr2[3,1])

# print element 60
print(arr2[1,2])

# print element 40
print(arr2[1,0])

# print element 90
print(arr2[2,2])

# print element 30
print(arr2[0,2])

# print element 70
print(arr2[2,0])

# print element 100
print(arr2[3,0])

# print element 120
print(arr2[3,2])


[10 20 30 40 50 60]
40
[60 50 40 30 20 10]
20
[30 40 50 60]
[40 30 20]
[30 20 10]
[40 50 60]
[10 20 30 40]
110
60
40
90
30
70
100
120


## 3-D array Indexing And Slicing

In [3]:
import numpy as np

arr3D = np.array([
    [   # Layer 0 For Indexing the Layer starts with 0
        [10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 100, 110, 120]
    ],

    [   # Layer 1
        [130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]
    ]
])

print(arr3D[0, :1]) # Targets the First 2-D layer
print(arr3D[1, :1]) # Targets the Second 2-D Layer

# Questions 
# Extract Layer 0
print(arr3D[0, : ]) 

# Extract Layer 1
print(arr3D[1,:])

# Extract the Element 190
print(arr3D[1,])

# Extract the Follwing 
# [[50 60 70 80]
# [90 100 110 120]]
print(arr3D[0, 1:, ])

# Extract the Follwing
# [[170 180 190 200]
# [210 220 230 240]]
print(arr3D[1, 1:])

# Extract the Following
# [[ 20  30]
# [ 60  70]
# [100 110]]
print(arr3D[0, :, 1:3])

# Extract the Following
# [[150 160]
# [190 200]
# [230 240]]
print(arr3D[1, :, 2:])

# Extract the Following
# [[110 120]
# [230 240]]
print(arr3D[:,2, 2: ])


[[10 20 30 40]]
[[130 140 150 160]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[130 140 150 160]
 [170 180 190 200]
 [210 220 230 240]]
[[130 140 150 160]
 [170 180 190 200]
 [210 220 230 240]]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[[170 180 190 200]
 [210 220 230 240]]
[[ 20  30]
 [ 60  70]
 [100 110]]
[[150 160]
 [190 200]
 [230 240]]
[[110 120]
 [230 240]]


### Negative Slicing 3-D array

In [9]:
# Extract Layer 1 using negative indexing.
print(arr3D[1, -3:])

# Extract the Following
# [210 220 230 240]
print(arr3D[1, 2])

# Extract the Following
# [[110 120]
# [230 240]]
print(arr3D[:,2,2:])

# Extract the Following
# [[240 230 220 210]
# [200 190 180 170]
# [160 150 140 130]]
print(arr3D[1, ::-1,::-1])


# Extract the following Sub-array
#  [[[ 50  60  70  80]
#   [ 90 100 110 120]]

#  [[170 180 190 200]
#   [210 220 230 240]]]
print(arr3D[:, 1:, :])

# Extract the following sub-array 
# [[[160 150]
#   [200 190]
#   [240 230]]

#  [[ 40  30]
#   [ 80  70]
#   [120 110]]]
print(arr3D[::-1,:,-1:-3:-1])

[[130 140 150 160]
 [170 180 190 200]
 [210 220 230 240]]
[210 220 230 240]
[[110 120]
 [230 240]]
[[240 230 220 210]
 [200 190 180 170]
 [160 150 140 130]]
[[[ 50  60  70  80]
  [ 90 100 110 120]]

 [[170 180 190 200]
  [210 220 230 240]]]
[[[160 150]
  [200 190]
  [240 230]]

 [[ 40  30]
  [ 80  70]
  [120 110]]]


## Fancy Indexing VS Normal Indexing

In [13]:
arr1D = np.array([10,20,30,40,50,60])

# Normal Indexing
print(arr1D[0]) # Retrieves element 10 from the array

print(arr1D[5]) # Should Retrieve element 60 from the array

print(arr1D[10,20]) # Crashing the code by passing more than one indexes

10
60


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

#### Fancy indexing comes to play

In [20]:
# Fancy Indexing

print(arr1D[[0,1,2]]) # Retrieves 10,20,30



[10 20 30]


#### Fancy Indexing on 1-D Array

In [ ]:
arr1D = np.array([10,20,30,40,50,60,70,80,90])

# Can Retrieve multiple elements now
print(arr1D[[0, 3, 7]]) # 10 40 80

print(arr1D[[8,4,2]]) # 90 50 30

print(arr1D[[5, 0, 8]]) # 60 10 90

print(arr1D[[4, 7, 3]]) # 50 80 40

# Same Element 3 Times
print(arr1D[[7, 7, 7]]) # 80 80 80

[10 40 80]
[90 50 30]
[60 10 90]
[50 80 40]
[80 80 80]


#### Fancy Indexing on 2-D array (Row)

In [ ]:
arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

# print Row 0 and 3
print(arr2d[[0, 3]])
# [[ 10  20  30]
#  [100 110 120]]

# print Row 1 and 2
print(arr2d[[1, 2]])
# [[40 50 60]
#  [70 80 90]]

[[ 10  20  30]
 [100 110 120]]
[[40 50 60]
 [70 80 90]]


#### Fancy Indexing on 2-D array (Rows and Columns)

In [ ]:
arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

# Print Column 1 and 2
print(arr2d[:, [1,2]])
# [[ 20  30]
#  [ 50  60]
#  [ 80  90]
#  [110 120]]

# Print column 0 and 3
print(arr2d[:, [0, 2]])
# [[ 10  30]
#  [ 40  60]
#  [ 70  90]
#  [100 120]]


[[ 20  30]
 [ 50  60]
 [ 80  90]
 [110 120]]
[[ 10  30]
 [ 40  60]
 [ 70  90]
 [100 120]]


#### Questions

In [ ]:
import numpy as np

arr2D = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90,100,110,120],
    [130,140,150,160]
])

# Using Fancy Indexing, extract:
# [[10 20 30 40]
#  [90 100 110 120]]
print(arr2D[[0,2]])

# Using Fancy Indexing, extract:
# [[20 40]
#  [60 80]
#  [100 120]
#  [140 160]]
print(arr2D[:, [1,3]])

# Using Fancy Indexing, extract:
# [[50 60 70 80]
#  [130 140 150 160]]
print(arr2D[[1,3]])

# Using Fancy Indexing, extract:
# [[10 30]
#  [90 110]]
print(arr2D[::2, [0,2]])

# Using Fancy Indexing, extract:
# [[130 140 150 160]
#  [10 20 30 40]]
print(arr2D[[3, 0]])

# Using Fancy Indexing, extract:
# [[40 20]
#  [80 60]
#  [120 100]
#  [160 140]]
print(arr2D[:,[3, 1]])

# Using Fancy Indexing, extract:


[[ 10  20  30  40]
 [ 90 100 110 120]]
[[ 20  40]
 [ 60  80]
 [100 120]
 [140 160]]
[[ 50  60  70  80]
 [130 140 150 160]]
[[ 10  30]
 [ 90 110]]
[[130 140 150 160]
 [ 10  20  30  40]]
[[ 40  20]
 [ 80  60]
 [120 100]
 [160 140]]


#### Fancy-Assignment 1-D array

In [50]:
arr1D = np.array([10,20,30,40,50,60,70])

# Changes the value of the specified indexes
arr1D[[0, 3, 5]] = 999
print(arr1D)


arr1D[[1,2,4,6]] = 777
print(arr1D)

[999  20  30 999  50 999  70]
[999 777 777 999 777 999 777]


In [ ]:
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Target row 0 and 2
arr2[[0,2]] = [
    [10,20,30,40], # Assignes the Value to Row 0
    [100,110,120,130] # Assignes the Value to 1
]
print(arr2)

# Target the Row 0 and 2 and Change all the value to 77
arr2[[0,2]]= 77
print(arr2)

# Target the column 0 and 3 and change all the value to 999
arr2[:, [0,3]] = 999
print(arr2)

# Target the Column 1 and 2 and change all the value to 777
arr2[:, [1,2]]= 777
print(arr2)

[[ 10  20  30  40]
 [  5   6   7   8]
 [100 110 120 130]]
[[77 77 77 77]
 [ 5  6  7  8]
 [77 77 77 77]]
[[999  77  77 999]
 [999   6   7 999]
 [999  77  77 999]]
[[999 777 777 999]
 [999 777 777 999]
 [999 777 777 999]]


##### Questions on Fancy Indexing and Assignment 

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

# Using Fancy Indexing, extract:
# [10 40 70]
print(arr[[0,3,6]])

# Using Fancy Indexing, extract:
# [80 20 50]
print(arr[[7,1,4]])

#Using Fancy Assignment, replace the elements at indices 1, 4, and 6 with 999.
arr[[1,4,6]] = 999
print(arr)

# Replace 10, 40, 80 with 100, 400, 800
arr[[0, 3, 7]] = 100, 400, 800
print(arr)


[10 40 70]
[80 20 50]
[100  20  30 400  50  60  70 800]


In [74]:
arr2D = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
    [130,140,150,160]
])


# Using Fancy Indexing, extract:
# [[10 20 30 40]
#  [90 100 110 120]]
print(arr2D[[0, 2, ]])

# Using Fancy Indexing, extract:
# [[20 40]
#  [60 80]
#  [100 120]
#  [140 160]]
print(arr2D[:, [1,3]])

# Using Fancy Indexing, extract:
# [[130 140 150 160]
#  [50 60 70 80]]
print(arr2D[[3,1]])

# Using Fancy Indexing, extract:
# [[30 20]
#  [70 60]
#  [110 100]
#  [150 140]]
print(arr2D[:, [2,1]])

# Using Fancy Assignment, replace rows 1 and 3 with 0.
# Expected Output

# [[ 10  20  30  40]
#  [  0   0   0   0]
#  [ 90 100 110 120]
#  [  0   0   0   0]]
# arr2D[[1,3]] = 0
# print(arr2D)

# Using Fancy Assignment, replace columns 0 and 2 with 999.
# Expected Output

# [[999  20 999  40]
#  [999  60 999  80]
#  [999 100 999 120]
#  [999 140 999 160]]
arr2D[:,[0,2]] = 999
print(arr2D)

[[ 10  20  30  40]
 [ 90 100 110 120]]
[[ 20  40]
 [ 60  80]
 [100 120]
 [140 160]]
[[130 140 150 160]
 [ 50  60  70  80]]
[[ 30  20]
 [ 70  60]
 [110 100]
 [150 140]]
[[999  20 999  40]
 [999  60 999  80]
 [999 100 999 120]
 [999 140 999 160]]


## Problem with Normal Indexing and Fancy Indexing

In [75]:
arr = np.arange(1,101) # Here we have a array of 100 elements

print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
# Fancy Indexing
print(arr[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])


[ 11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Solution Using Boolean Masking

In [79]:
print(arr[ arr > 10])

[ 11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


#### Ways to create a Mask

In [81]:
# By Creating a Variable

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

mask = arr > 10
print(arr[mask]) # Print the element which are > 10

# Pass the Condition 
print(arr[arr > 10])



[15 20 25 30 35 40 45 50]
[15 20 25 30 35 40 45 50]


##### Questions on BM

In [90]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# Retrieve all elements greater than 20.
print(arr[arr > 20])
# or 
# mask = arr > 20
# print(arr[mask])

# Retrieve all elements less than 30.
print(arr[ arr < 30 ])

# Retrieve all elements greater than or equal to 35.
print(arr[arr >= 35])

# Retrieve all elements less than or equal to 15.
print(arr[arr <= 15])

# Boolean Masking on 2-D array
arr2D = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])


print(arr2D[arr2D > 40])

print(arr2D[arr2D <= 30])


# Boolean Masking on a 3-D array
arr3D = np.array([
    [
        [10,20],
        [30,40]
    ],
    [
        [50,60],
        [70,80]
    ]
])

print(arr3D[arr3D >= 35])

print(arr3D[arr3D <= 20])

[25 30 35 40 45 50]
[ 5 10 15 20 25]
[35 40 45 50]
[ 5 10 15]
[50 60 70 80 90]
[10 20 30]
[40 50 60 70 80]
[10 20]


## np.where()

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

result = np.where(arr > 50, 999, arr)
print(result)
print(result.ndim)

[ 10  20  30  40  50 999 999 999]
1


#### Returns the Index of of the element

In [21]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Return the indices of all elements greater than 40.
print(np.where(arr > 40)) # 4,5,6,7

# find the index of element 50
print(np.where(arr == 50))

# Return the indices of all elements less than or equal to 30.
print(np.where(arr <= 30))

# Return the indices of all elements equal to 60.
print(np.where(arr == 60))

# Return the indices of all elements not equal to 50.
print(np.where(arr != 50))

# Store the indices of all elements greater than or equal to 50 in a variable named indices.
indices = np.where( arr >= 50)
print(indices)


arr2D = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Return the indices of all elements greater than 50.
print(np.where(arr2D > 50))

(array([4, 5, 6, 7]),)
(array([4]),)
(array([0, 1, 2]),)
(array([5]),)
(array([0, 1, 2, 3, 5, 6, 7]),)
(array([4, 5, 6, 7]),)
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))


#### Replace Elements based on conditions

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

# Replace every value greater than 40 with 999.
print(np.where(arr > 40, 999, arr))

# Replace every value less than or equal to 30 with 0.
print(np.where(arr <= 30, 0, arr))

# Replace every even number with -1.
print(np.where(arr % 2 == 0, -1, arr))

# Replace every value greater than or equal to 50 with "Pass" and the remaining values with "Fail".
print(np.where(arr >= 50, "Pass", "Fail"))

# Create a new array where
# values less than 50 become 100
# values greater than or equal to 50 remain unchanged.
result = np.where(arr < 50, 100, arr )
print(result)

# Create a new array where
# values divisible by 20 become 999
# all other values remain unchanged.
result = np.where(arr % 20 == 0, 999, arr)
print(result)

arr2D = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

# Replace every value greater than 50 with 0.
print(np.where(arr2D > 50, 0, arr2D))

# Replace every value less than or equal to 40 with 999.
print(np.where(arr2D <= 40, 999, arr2D))


arr = np.array([5,10,15,20,25,30,35,40])

# Create a new array where
# values greater than or equal to 20 become their square
# values less than 20 remain unchanged.
result = np.where(arr >= 20, arr**2, arr)
print(result)
print(arr)

[   5   10   15  400  625  900 1225 1600]
[ 5 10 15 20 25 30 35 40]
