# Methods of Creating an Array in Numpy

## 1. np.array()

#### Creating 1-D array using np.array()

In [3]:
import numpy as np

arr_1D = np.array([10,20,30,40]) # Passing the python list to the function np.array() which will convert the list to an array
print(arr_1D)

print(type(arr_1D))



arr = np.array([1,2,3])

print(arr.ndim) # 1-D array
print(arr.shape) # No Rows no Column, there are just 3 elements in one dimension


another_1D = np.array(["Lewis", "Max", "Senna"]) # No Row No colum, just 3 elements in one axis (1 Dimension) 
print(another_1D)

print(another_1D.shape) # (3,) contains 3 elements 
print(another_1D.ndim) # 1 - D array


[10 20 30 40]
<class 'numpy.ndarray'>
1
(3,)
['Lewis' 'Max' 'Senna']
(3,)
1


#### Creating 2-D array using np.array()

In [6]:
import numpy as np

arr2 = np.array([[10, 20, 30, 40]]) # This is a nested list because there is a list inside another list (Nested List)
print(arr2.shape) # 2-D array
print(arr2.ndim) # (1, 4) --> 1 Row, 4 Column
 
arr_2D = np.array([
  #col1, col2
    [10, 20], # Row1
    [30, 40]  # Row 2
]) # 2-D List (2 list are passed inside a list (Nested Formation) )

print(arr_2D.ndim) # 2
print(arr_2D.shape) # 2x2 

(1, 4)
2
2
(2, 2)


##### Example 2

In [ ]:
import numpy as np

arr_2 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) # 2-D array of shape 4x4 (4 Rows & $ Columns)

print(arr_2.ndim) # 2
print(arr_2.shape) # 4x4
print(arr_2.size) # 16 elements are inside this array

print(arr_2)

2
(4, 4)
16
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### Creating 3-D array using np.array() 

In [ ]:
import numpy as np

arr_3D = np.array([
    [
        [10,20,30,40], 
        [50,60,70,80],
        [90, 100, 110, 120]
    ] 
])

print(arr_3D.ndim) # 3-D Array


3


##### Example 2

In [ ]:
import numpy as np

arr_3 = np.array([
    [[10, 20, 30], [40, 50, 60]],
    [[70, 80, 90], [100, 110, 120]]
])

print(arr_3.ndim) # 3-D array

3


##### Example 3

In [ ]:
arr3 = np.array([
    [       # Layer (1) 2-D array
        [10,20], # row 1
        [30,40]  # row 2
    ],

    [       # Layer (2) 2-D array
        [50,60], # row 1
        [70,80] # row 2

    ]
])


print(arr3)
print(arr3.ndim)
print(arr3.shape) # (2,2,2) --> (2) layer of 2-D array, 2-Rows, 2-Cloumn 
# (Layers, Rows, Columns)
# (2 Layers, 2 Rows, 2 Columns)






[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3
(2, 2, 2)


#### 3-D Array with multiple 2-D layers

In [21]:
import numpy as np

layer_1 = np.array([
    [  # Layer 1
        [10,20,30],
        [40,50,60]
        
    ]
])

print(layer_1.shape) # only 1 layer of 2-D array



layer_2 = np.array([

    [ # Layer 1
        [10,20],
        [30,40]
    ],
    [ # Layer 2
        [1,2],
        [3,4]

    ]
])

print(layer_2.shape) # 2 Layers of 2-D array


layer_3 = np.array([
    [  # Layer 1
        [10,20],
        [30,40]
    ],
    [  # Layer 2
        [1,2],
        [3,4]
    ],
    [  # Layer 3
        [1,0],
        [0,1]
    ]
])

print(layer_3.shape) # 3 Layers of 2-D Array


(1, 2, 3)
(2, 2, 2)
(3, 2, 2)


## Glimps for 4-D array

In [ ]:
import numpy as np

arr_4D = np.array([
    [ # 1 Layer of 2-D array
        [ # 1 Layer of 3-D array
            [10,20],
            [30,40]
        ]
    ]
])


print(arr_4D.shape)
print(arr_4D.ndim)

(1, 1, 2, 2)
4


In [24]:
import numpy as np

arr4 = np.array([
    [
        [
            [10,20],
            [30,40]
        ],
        [
            [1, 2],
            [4, 5],
            
        ]
    ]
])

print(arr4.ndim)
print(arr4.shape)

4
(1, 2, 2, 2)


## 2. np.zeros()

### 1-D array using np.zeros

In [ ]:
import numpy as np

zero_matrix = np.zeros(3) # Returns a 1-D array containing 3-zeros 

print(zero_matrix) # [0, 0, 0]
print(zero_matrix.shape) # (3,)

[0. 0. 0.]
(3,)


##### Example 2

In [ ]:
import numpy as np


arr_1 = np.zeros(5) # Returns a 1-D array of 5-zeros 

print(arr_1)
print(arr_1.shape) # (5,)

[0. 0. 0. 0. 0.]
(5,)


### 2-D array using np.array()

In [4]:
arr0_2d = np.zeros((3, 4)) # Creates a 2-D Array of 3-Rows and 4-columns (and value all set to "0")

print(arr0_2d)
print(arr0_2d.ndim) # 2
print(arr0_2d.shape) # (3, 4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)


##### Example 2

In [7]:
arr5 = np.zeros((4,3)) # Returns a 2-D array of 4-rows and 3-columns

print(arr5)
print(arr5.ndim)
print(arr5.shape)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(4, 3)


### 3-D arrays using np.zeros()

In [8]:
arr3d = np.zeros((1, 4, 3)) # Returns a 3-D array of 4-Rows and 3-Columns inside 1-Layer of 2-d array

print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
(1, 4, 3)


##### Example 2


In [9]:
arr03 = np.zeros((2, 2, 2)) # Create a Array of 2-Rows and 2-Columns with 2-Layers of 2-D array

print(arr03)
print(arr03.ndim)
print(arr03.shape)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3
(2, 2, 2)


## 3. np.ones()

### 1-D using np.ones()

In [1]:
import numpy as np

array_ones = np.ones(5) # Creates a 1-D Array of 5 "1" elements

print(array_ones)
print(array_ones.shape)
print(array_ones.ndim)



[1. 1. 1. 1. 1.]
(5,)
1


##### Example 2

In [2]:
arr_one = np.ones(3) # Creates a 1-D Array with 3 "1" element in it

print(arr_one)
print(arr_one.ndim)
print(arr_one.shape)

[1. 1. 1.]
1
(3,)


### 2-D using np.ones()

In [ ]:
# array_2 = np.ones((3,4)) # Creates a 2-D array of "1" with 3-Rows and 4-Columns

# print(array_2)
# print(array_2.shape)
# print(array_2.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
2


##### Example 2

In [ ]:
# array_1 = np.ones((4,2)) # Creates a 2-D array of "1" with 4-Rows and 2-Column

# print(array_1)
# print(array_1.shape)
# print(array_1.ndim)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(4, 2)
2


### 3-D Using np.ones()

In [6]:
array_2 = np.ones((2,3,4)) # Creates a 3-D array of "1" with 2-Layers of 2D array with 3-Rows and 4-Columns

print(array_2)
print(array_2.shape)
print(array_2.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)
3


##### Example 2


In [7]:
array_1 = np.ones((3,4,2)) # Creates a 3-d array 4-Rows and 2-Columns with 2-Layer of 2-D array
print(array_1)
print(array_1.shape)
print(array_1.ndim)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 2)
3


## 4. np.full()

### 2-D using np.full()

In [ ]:
arr_f = np.full((3,4),7) # Creates a 2-D array of 3-Rows and 4-Columns with constant value 7

print(arr_f)
print(arr_f.shape)
print(arr_f.ndim)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
(3, 4)
2


##### Example 2

In [12]:
Arr = np.full((4, 4), 10) # Creates a 2-D array of 4-Rows and 4-Columns with constant value 10

print(Arr)
print(Arr.shape)
print(Arr.ndim)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
(4, 4)
2


### 1-D using np.full() 

In [ ]:
arr_1DF = np.full(4,7) # Creates a 1-D array with 4 elements, with constant value 7

print(arr_1DF)
print(arr_1DF.shape)
print(arr_1DF.ndim)

[7 7 7 7]
(4,)
1


##### Example 2

In [10]:
arr_F = np.full(10, 9) # Creates a 1-D array with 10 elements, with constant value 9

print(arr_F)
print(arr_F.shape)
print(arr_F.ndim)

[9 9 9 9 9 9 9 9 9 9]
(10,)
1


### 3-D using np.full()

In [13]:
Arr3 = np.full((2, 4, 3),7) # Creates a 3-D array of 2layers of 2-D array with 4-Rows and 3-columns with constant value 7

print(Arr3)
print(Arr3.shape)
print(Arr3.ndim)

[[[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  [7 7 7]]]
(2, 4, 3)
3


##### Example 2

In [14]:
Ar4 = np.full((3, 2, 2),10) # Creates a 3-D array of 3-layers of 2-D array with 2-Rows and 2-columns with constant value 10

print(Ar4)
print(Ar4.shape)
print(Ar4.ndim)


[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]
(3, 2, 2)
3


## 5. np.eye()

In [15]:
arr_e = np.eye(5) # Creates a 2-d array of identity marix containing 5 0nes in the diagonal and rest of the value Zeros

print(arr_e)
print(arr_e.ndim) # 2
print(arr_e.shape) # 5x5

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
(5, 5)


##### Example 2

In [16]:
arr_e1 = np.eye(4) # Creates a 2-D array of 4 ones in the diagonal

print(arr_e1)
print(arr_e1.shape) # 4x4
print(arr_e1.ndim) # 2

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
2


#### Rows and Columns in np.eye()

In [17]:
cust = np.eye(3, 4) # Creates a 2-D array of Identity Matrix with 3-Rows and 4-columns

print(cust)
print(cust.shape) # (3,4)
print(cust.ndim) # 2



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
(3, 4)
2


In [18]:
cust1 = np.eye(6,6) # Creates a 2-D array of identical-Matrix with 6-Rows and 6-columns

print(cust1)
print(cust1.shape) # (6,6)
print(cust1.ndim)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
(6, 6)
2


## 6. np.arange()

In [20]:
# I am expecting it to create a 1-D array

arrge = np.arange(1, 11) # Start at "1" and End at "10"

print(arrge)
print(arrge.ndim) # 1
print(arrge.shape) # (10,)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
arrge1 = np.arange(1, 11, 2) # Start at 1, end at 10 and skip 2 numbers

print(arrge1) # (1,3,5,7,9)
print(arrge1.shape) # (5,)
print(arrge1.ndim)


[1 3 5 7 9]
(5,)
1


#### Using only Stop parameter

In [2]:
import numpy as np

arr = np.arange(11) # The array will stop at value 10, 11 is excluded

print(arr) 
print(arr.ndim) # # np.arange() Always creates a 1-D Array
print(arr.shape) # (11,) Because it starts form 0 


arr1 = np.arange(101) # Creates an array of elements starting form 0 to 100

print(arr1)
print(arr1.ndim)
print(arr1.shape) # (101)


[ 0  1  2  3  4  5  6  7  8  9 10]
1
(11,)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
1
(101,)


#### Using start and stop parameter

In [8]:
arr2 = np.arange(1, 11) # Array containis the elements starting form 1 to 10 

print(arr2)
print(arr2.shape)


arr3 = np.arange(10, 51) # Start from 10 and ends at 50

print(arr3)
print(arr3.shape)



[ 1  2  3  4  5  6  7  8  9 10]
(10,)
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
(41,)


#### Using Start, stop, Step parameter in np.arange()

In [14]:
arr = np.arange(10, 101, 10)

print(arr)
print(arr.shape)


arr1 = np.arange(1, 11, 2) # (1, 3, 5, 7, 9)

print(arr1)
print(arr1.shape)


# Negative Array
arr2 = np.arange(10, 0, -1) # -1 is compulsary or else the code will return an empyt array
# the -1 helps the array to print the negative numbers

print(arr2)



arr3 = np.arange(50, 0, -10)

print(arr3)

[ 10  20  30  40  50  60  70  80  90 100]
(10,)
[1 3 5 7 9]
(5,)
[10  9  8  7  6  5  4  3  2  1]
[50 40 30 20 10]


## 7.np.linspace()

In [ ]:
arr = np.linspace(0, 1, 50) 

print(arr)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [18]:
arr2 = np.linspace(1, 5, 10) # Returns 10 equal spaced numbers for range 1 to 5

print(arr2)
print(arr2.ndim) # always returns a 1-D array
print(arr2.shape) # i know i want 10 number 

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
1
(10,)


In [20]:
arr3 = np.linspace(1, 2, 5) # Returns 5 equal space values form range 1 to 2

print(arr3)

print(arr3.ndim) # Returns 1-D Array all the time


[1.   1.25 1.5  1.75 2.  ]
1


## 8. np.empty()

In [ ]:
arr_1D = np.empty(7) # Creates a 1-D array with 7 garbage value

print(arr_1D)


arr_2D = np.empty((4,4)) # Creaqtes a 2-D array of 4-Rows and 4-Columns with random garbage values
print(arr_2D)




[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.22647253e-307
 1.89146896e-307 7.56571288e-307 3.14082867e-317]
[[4.67296746e-307 1.69121096e-306 3.22647253e-307 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 3.49698923e-317]]


In [32]:
arr_3D = np.empty((2, 4, 4)) # Creates a 3-D Array of 2-Layeres of 2-D Array each 2-D array contains an array of 4-Rows and 4-Columns

print(arr_3D)
print(arr_3D.ndim)

[[[1.43544647e-311 1.09188508e-321 0.00000000e+000 0.00000000e+000]
  [1.43446915e-311 5.02034658e+175 5.98907849e-038 5.29168865e+174]
  [1.50161906e-076 7.60652296e-042 1.81370867e-052 7.75835242e-144]
  [3.59751658e+252 1.70100503e+256 4.87320288e+199 1.43212699e+161]]

 [[1.47762365e+248 1.16096346e-028 2.14027814e+161 4.96212127e+180]
  [1.94919988e-153 6.81788968e-038 1.42457987e+160 2.03873512e+184]
  [5.40128441e-062 1.41528119e+161 1.56602272e-076 3.11550433e-033]
  [9.71813159e-067 2.63182642e-052 1.14484251e+243 2.59903827e-144]]]
3


#### 1-D array using np.empty()

In [27]:
empty_array = np.empty(10) # Creates a 1-D array with 10 garbage values init

print(empty_array)
print(empty_array.ndim) # 1 


empty = np.empty(7) 

print(empty)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
1
[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.22647253e-307
 1.89146896e-307 7.56571288e-307 3.14082867e-317]


#### 2-D array using np.empty()

In [29]:
empty_2D = np.empty((4, 4)) # Creates a 2-D array of 4-Rows and 4-Columns with garbage value init

print(empty_2D) 
print(empty_2D.ndim)


empty_2 = np.empty((2, 2)) 

print(empty_2)
print(empty_2.ndim)

[[4.67296746e-307 1.69121096e-306 3.22647253e-307 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 3.49698923e-317]]
2
[[7.74860416e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]]
2


#### 3-D arry using np.empty()

In [30]:
array_3D = np.empty((3, 2, 2)) # Creates a 3-D array of 3 layered 2-D arrays inti of 2 rows and 2 columns with garbage values init

print(array_3D)
print(array_3D.ndim)

[[[1.43544452e-311 2.81617418e-322]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 3.69776220e-062]
  [7.12441771e-091 1.69175718e-052]]

 [[8.41003923e+164 3.56716416e-057]
  [6.48224659e+170 4.93432906e+257]]]
3


## 9. np.random.rand()

#### 1-D array using np.random.rand()

In [36]:
arr_1d = np.random.rand(7) # Creates a 1-D array of 7 random values in range 0-inclusive to 1-exclusive

print(arr_1d)
print(arr_1d.ndim)

arr1D = np.random.rand(10)

print(arr1D)

[0.31980221 0.70707158 0.67790701 0.90174642 0.10350807 0.97594486
 0.98123404]
1
[0.38670517 0.78988728 0.49018826 0.20889837 0.00903579 0.51618172
 0.85202961 0.93065042 0.94132473 0.16783126]


#### 2-D array using np.random.rand()

In [39]:
arr_2D = np.random.rand(2,2)

print(arr_2D)


arr2 = np.random.rand(4, 5)
print(arr2)
print(arr2.ndim)



[[0.22215737 0.82887766]
 [0.18112579 0.34138266]]
[[0.89653054 0.79699386 0.04779809 0.10853175 0.82806353]
 [0.61178188 0.04705568 0.00317269 0.16563954 0.29535952]
 [0.01066385 0.28344733 0.23246497 0.56630951 0.32954889]
 [0.23358544 0.63054248 0.90916129 0.16065846 0.56856116]]
2


#### 3-D array using np.random.rand()

In [40]:
array_3D = np.random.rand(3, 3, 2) 

print(array_3D)
print(array_3D.ndim)

[[[0.24354474 0.50088284]
  [0.00874592 0.5240261 ]
  [0.58726654 0.71224211]]

 [[0.85263786 0.56664008]
  [0.38302955 0.81213652]
  [0.40728148 0.61301447]]

 [[0.40457358 0.58771384]
  [0.40610161 0.89370502]
  [0.34985612 0.70963324]]]
3


In [41]:
array3d = np.random.rand(2, 4, 4)

print(array3d)

[[[0.1959809  0.67416423 0.39510398 0.39240001]
  [0.12947197 0.39495523 0.9231275  0.66378907]
  [0.68119653 0.80783836 0.33624689 0.6965085 ]
  [0.87930042 0.53059457 0.15595753 0.99559883]]

 [[0.87737746 0.57630329 0.59373975 0.25819876]
  [0.50318019 0.96050676 0.25131276 0.14350467]
  [0.07667436 0.81854003 0.73912394 0.28756084]
  [0.32790151 0.31682226 0.84642713 0.11216632]]]
