## Array Attributes in Numpy

### ndim (Number of Dimensions)

In [5]:
import numpy as np

arr_1D = np.array([10,20,30,40,50])

print(arr_1D.ndim)

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr.ndim)

arr_2D = np.array([
    [1,2,3,4],
    [10,20,30,50]
])

print(arr_2D)
print(arr_2D.ndim)


arr_3D = np.array([
    [  # Layer 1 of 2-D array
        [10,20],
        [30,40]
    ],
    [  # Layer 2 of 2-D array
        [50,60],
        [70,80]

    ],
    [  # Layer 3 of 2-D array
        [90,100],
        [110,120]

    ]
])

print(arr_3D.ndim) # 3-D array
print(arr_3D) 



array_3D = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [11,12,13,14],
        [15,16,17,18]
    ]
])

print(array_3D) # 3-D array of 2 Rows and 4 columns
print(array_3D.ndim)
print(array_3D.shape)

1
2
[[ 1  2  3  4]
 [10 20 30 50]]
2
3
[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
3
(2, 2, 4)


### shape (Returns the number of elements in each axis)

In [14]:
arr = np.array([10,20,30,40])

print(arr.shape) # (4,) --> 4 elements in one Axis
print(arr.ndim) # 1-D array

arr_1d = np.zeros(7)

print(arr_1d.shape) # (7,) --> 7 elements in one Axis (Axis 0)
print(arr_1d.ndim)
print(arr_1d)


arr2d = np.array([
    [2,3,4,5],
    [6,7,8,9],
    [10,11,12,13]
])

print(arr2d.shape) # (3,4) --> 3-Rows and 4-Columns
print(arr2d.ndim) # 2-D array
print(arr2d)


arr2_D = np.full((3,4),7) # Returns a 2-D array of all elements initialized to 7

print(arr2_D.shape) # (3,4) --> 3-Rows and 4-Columns
print(arr2_D.ndim) # 2-D 
print(arr2_D) 




arr_3D = np.array([
    [
        [10,20],
        [30,40]
    ],
    [
        [50,60],
        [70,80]

    ]
])

print(arr_3D.shape) # (2, 2, 2) # 2-Layeres of 2-D array, 2-Rows and 2-Columns
print(arr_3D.ndim) # 3-D array
print(arr_3D)





(4,)
1
(7,)
1
[0. 0. 0. 0. 0. 0. 0.]
(3, 4)
2
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
(3, 4)
2
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
(2, 2, 2)
3
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [18]:
arr_3 = np.empty((3,4,4)) # 3 layers of 2-D array with 4-Rows and 4-Columns
print(arr_3.shape) # (3,4,4)
print(arr_3.ndim) # 3-D array
print(arr_3)

(3, 4, 4)
3
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### size (total number of elements in the array)


In [ ]:
arr = np.array([10,20,30,40,50,60])

print(arr.size) # 6 --> There are 6 elements inside the 1-D array


arr_1D = np.array([100,90,80,70,60])

print(arr_1D.size) # 5 --> There are 5 elements inside this 1-D array
print(arr_1D.shape) # (5,)


arr2D = np.array([
    [10,20,30,40],
    [50,60,70,80]
])

print(arr2D.size) # 8--> There are 8 elements inside this 2-D Array
print(arr2D)


arr_2D = np.full((3,4),10)

print(arr_2D.size) # 12 elements of "10" are present inside the array
print(arr_2D)



arr_3D = np.random.rand(2, 3, 4) # 3-D array with 2-Layers of 2-D array with 3-rows and 4-Columns

print(arr_3D.size)
print(arr_3D.ndim) # 3
print(arr_3D)





6
5
(5,)
8
[[10 20 30 40]
 [50 60 70 80]]
12
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
24
3
[[[0.77988492 0.18810737 0.36433345 0.33235672]
  [0.85690544 0.21271427 0.66244877 0.29779241]
  [0.63510349 0.92746165 0.96385821 0.00335211]]

 [[0.12865347 0.16927131 0.4091116  0.19756028]
  [0.17115315 0.15182687 0.34082543 0.51287242]
  [0.97881527 0.78653014 0.89077572 0.16859503]]]
48
3
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [27]:
arr3D = np.ones((3,4,4))

print(arr3D.size)
print(arr3D.ndim)
print(arr3D)

48
3
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## dtype

#### Integer datatype

In [ ]:
# 2-D array of integer data type
arr_2d = np.array([
    [10,20],
    [30,40]
])

print(arr_2d.dtype)

# 3-D array of integer data type
arr_3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(arr_3d.dtype)


int64
int64


#### Float Datatype

In [ ]:
# 2-D array of float data type
arr2d = np.array([
    [3.14, 2.17, 7.91],
    [5.55, 3.12, 69.69]
])

print(arr2d.dtype)


# 3-D array of float data type
arr3d = np.random.rand(2,3,3)

print(arr3d)
print(arr3d.dtype)

float64
[[[0.7476926  0.97174096 0.66778299]
  [0.07979811 0.10327638 0.20370095]
  [0.26556532 0.47970248 0.3825641 ]]

 [[0.38432075 0.64360175 0.31017435]
  [0.98086526 0.07423289 0.79338611]
  [0.93210204 0.39379265 0.40535993]]]
float64


#### String Datatype

In [33]:
# 1-D array of String Datatype
worldcup = np.array(["France","Portugal","Spain","England","Robbers","Egypty"])

print(worldcup.dtype)

# 2-D array of String Datatype
arr2d = np.full((3,4),"CR7")
print(arr2d.dtype)
print(arr2d)


<U8
<U3
[['CR7' 'CR7' 'CR7' 'CR7']
 ['CR7' 'CR7' 'CR7' 'CR7']
 ['CR7' 'CR7' 'CR7' 'CR7']]


#### Boolean Datatype

In [ ]:
# 1-D array of Boolean datatype values
arr = np.array([True, False, False, True])

print(arr.dtype)

# 3-D array of boolean datatype values
arr3d = np.full((2, 2, 2), True)

print(arr3d)
print(arr3d.dtype)

bool
[[[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]
bool


## itemsize

#### Integer Array

In [35]:

# 1-D array of integer datatype
arr = np.array([10, 20, 30, 40])

print(arr.dtype)
print(arr.itemsize) # 8 Each element inside that array is of 8 byte

int64
8


#### Floating-point Array

In [38]:
arr1 = np.array([3.14, 5.12, 69.69, 67.67])

print(arr1.dtype) # Float
print(arr1.itemsize)


arr2 = np.array([
    [10.9,20.6,30.2],
    [40.67,50.90,6.23]
])

print(arr2.dtype)
print(arr2.itemsize)

float64
8
float64
8


#### Boolean Array


In [40]:
# 1-D array of Boolean Datatypes
arr = np.array([True, False, True, False])

print(arr.dtype)
print(arr.itemsize) # "1" Size of Each element inside this array


# 2-D array of Boolean Datatypes
arr2 = np.full((3, 4),False)

print(arr2.dtype)
print(arr2.itemsize)



bool
1
bool
1


## nbytes

In [ ]:
arr = np.array([10,20,30,40,50]) 

print(arr.dtype) # int64
print(arr.itemsize) # 8 byte (we know integer datatype takes 8 byte)
print(arr.nbytes) # 8 x 5 = 40 bytes --> Total size of the array

int64
8
40


In [42]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr.itemsize) # 8 byte
print(arr.size) # 6
print(arr.nbytes) # 48 --> itemsize x size --> 8 x 6 = 48

8
6
48
