# 1. reshape()

#### Rule for np.reshape() ie 
Total Elements Before = Total Elements After 

In [6]:
import numpy as np

old_1Darray = np.array([10,20,30,40,50,60]) # Total Elements Before = 6

new_2Darray = old_1Darray.reshape(2, 3) # 2x3 --> Total Elements after = 6

print(new_2Darray)



[[10 20 30]
 [40 50 60]]


### Reshaping 1-D array into 2-D array

In [ ]:
# Create a 1-d array of 6 elements and convert it into a 2-D array of (2,3) and (3,2)
import numpy as np


arr1D = np.array([10,20,30,40,50,60,70,80]) # There are 8 Elements in this 1-D array 
# Total Elements Before? --> 8 

# 2-Rows and 4-Columns
arr2D = arr1D.reshape(2,4) # 2x4 = 8 elements 
# Total Elements After? --> 8 ✅

# 4-Rows and 2-Columns
another_2D = arr1D.reshape(4,2) # 8 elements
# Total Elements After? --> 8 ✅


print(f"{arr2D} with {arr2D.ndim} Dimensions")
print(f"{another_2D}with {another_2D.ndim} Dimensions")

[[10 20 30 40]
 [50 60 70 80]] with 2 Dimensions
[[10 20]
 [30 40]
 [50 60]
 [70 80]]with 2 Dimensions


#### Example 2

In [8]:
# Creating a 1-D array of 10 elements
arr1 = np.arange(10,101,10) 
# [ 10  20  30  40  50  60  70  80  90 100] 
print(arr1)

# Reshaping the 1-D array into a 2-D array of 2-Rows and 5-Columns
print(arr1.reshape(2,5)) # 2x5 ie 10 elements after ✅

# Reshaping the same 1-D array into a 2-D array of 5-Rows and 2-columns
print(arr1.reshape(5,2))  # 5x2 ie 10 elements after ✅

[ 10  20  30  40  50  60  70  80  90 100]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


### Reshaping 2-D array into 1-D array

In [ ]:
# Here we have a 2-D array of shape 3-Rows and 2-Columns and Size 6
arr2d = np.array([
    [10,20],
    [30,40],
    [50,60]
])
# Total number of elements = 6

# Resahping the 2-D array into a 1-D array of 6 elements
arr1D = arr2d.reshape(6)

print(arr1D)
# [10 20 30 40 50 60] Total Number of elements after = 6 ✅

another_1D = arr2d.reshape(7) # This Should give me an error
print(another_1D) 

[10 20 30 40 50 60]


ValueError: cannot reshape array of size 6 into shape (7,)

### Reshaping 2-D array into 3-D array

In [ ]:
arr2D = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
]) 
# total Count = 12

# Reshaping it into 3-D array
arr3D = arr2D.reshape(2,3,2) # 2x3x2 = 12

print(arr3D)

# [[[ 10  20]
#   [ 30  40]
#   [ 50  60]]

#  [[ 70  80]
#   [ 90 100]
#   [110 120]]]

# Total Element after = 12 ✅

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]]


#### Example 2

In [ ]:
import numpy as np

arr2D = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200],
    [210, 220, 230, 240]
])
# total Count = 24

# Reshaping it into a 3-D array of 2-Layered 4-Rows and 3-Columns

arr3 = arr2D.reshape(2,4,3)
print(arr3)
# [[[ 10  20  30]
#   [ 40  50  60]
#   [ 70  80  90]
#   [100 110 120]]

#  [[130 140 150]
#   [160 170 180]
#   [190 200 210]
#   [220 230 240]]]

# Total Size After = 24 ✅

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]

 [[130 140 150]
  [160 170 180]
  [190 200 210]
  [220 230 240]]]


### Reshaping 3-D array into 2-D array

In [ ]:
arr3D = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [70,80,90],
        [100,110,120]
    ]
]) # Total Size of the Array = 12

# Reshaping into a 2-D array of 4-rows and 3-Columns --> (4x3) = 12 ✅
arr2d = arr3D.reshape(4,3)

print(arr2d)
# [[ 10  20  30]
#  [ 40  50  60]
#  [ 70  80  90]
#  [100 110 120]]

# Total Elements After = 12 ✅


ano2 = arr3D.reshape(2,6) # 2x6 = 12 ✅

print(ano2)
# [[ 10  20  30  40  50  60]
#  [ 70  80  90 100 110 120]]

# Total elements After 12 ✅




[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


# 2. ravel()

In [ ]:
arr3d = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [70,80,90],
        [100,110,120]
    ]
])

flat = arr3d.ravel() # Converts a Multi-dimensional array into a 1-D array(One Dimensional Array)
print(flat)
print(flat.ndim) # 1 Dimension

arr2d = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

flat1 = arr2d.ravel()
print(flat1)
print(flat1.ndim) # 1 Dimension

[ 10  20  30  40  50  60  70  80  90 100 110 120]
1
[10 20 30 40 50 60 70 80 90]
1


#### Example 2

In [ ]:
arr2d = np.full((3,4),7)

print(arr2d)
print(arr2d.ndim) # 2-D array

# Using ravel() we can Convert any Multi-Dimensional Array into a 1-D array
print(arr2d.ravel()) # [7 7 7 7 7 7 7 7 7 7 7 7]  --> 1-D array

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
2
[7 7 7 7 7 7 7 7 7 7 7 7]


In [27]:
arr3d = np.full((2,2,2), 7)
print(arr3d)


new_array = np.ravel(arr3d)

print(new_array)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
[7 7 7 7 7 7 7 7]


# 3. flatten()

In [28]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)


new_flatten = arr.flatten()
print(new_flatten)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


#### Example 2

In [29]:
arr3d = np.array([
    [
        [10,20,30],
        [40,50,60,]
    ],
    [
        [70,80,90],
        [100,110,120]
    ]
])
print(arr3d.ndim) # 3-d array

# Convert the 3-D array into a 1-D arrat using flatten()
new_array = arr3d.flatten()

print(new_array)
print(new_array.ndim) # 1-d array

3
[ 10  20  30  40  50  60  70  80  90 100 110 120]
1


# 4. transpose()

In [ ]:
# Example on a 2-D array
import numpy as np

arr2d = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [100,110,120,130]
]) 

# arr2d --> 3-Rows and 4-Columns

new_array = arr2d.transpose()
print(new_array)

# After Transpose the Rows Became the Column and Vice versa 
# 4-Rows and 3-Columns

[[ 10  50 100]
 [ 20  60 110]
 [ 30  70 120]
 [ 40  80 130]]


#### Example 2 (3-D array)

In [ ]:
arr3d = np.array([  # (2,2,3) --> (3,2,2) (3layers, 2Rows, 2Columns)
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [70,80,90],
        [100,110,120]
    ]
])
# Before Transpose (2,2,3) 2-Layers of 2-D array with 2-Rows and 3-Columns

new_arr = arr3d.transpose()
print(new_arr)



[[[ 10  70]
  [ 40 100]]

 [[ 20  80]
  [ 50 110]]

 [[ 30  90]
  [ 60 120]]]


In [ ]:
# Another Example 

arr3 = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [70,80,90],
        [100,110,120]

    ],
    [
        [130,140,150],
        [160,170,180]

    ]
])
# Before Transpose (3,2,3)

new_array = arr3.T
# According to the Formula it should become --> (Column, Row, Layers ) so (3,2,3)

print(new_array)

# After Transpose
# [[[ 10  70 130]
#   [ 40 100 160]]

#  [[ 20  80 140]
#   [ 50 110 170]]

#  [[ 30  90 150]
#   [ 60 120 180]]]

# (3,2,3) ✅


[[[ 10  70 130]
  [ 40 100 160]]

 [[ 20  80 140]
  [ 50 110 170]]

 [[ 30  90 150]
  [ 60 120 180]]]


# 5 .T

In [5]:
# Example on a 2-D array
import numpy as np

arr2d = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [100,110,120,130]
]) 

# arr2d --> 3-Rows and 4-Columns

new_array = arr2d.T
print(new_array)

# After Transpose the Rows Became the Column and Vice versa 
# 4-Rows and 3-Columns

[[ 10  50 100]
 [ 20  60 110]
 [ 30  70 120]
 [ 40  80 130]]


#### Example 2(Square Matrix)

In [ ]:
arr = np.array([
    [2,4],
    [6,8]
])

new_arr = arr.T
print(new_arr)

# After Transpose
# [[2 6]
#  [4 8]]

[[2 6]
 [4 8]]


# 6. swapaxes()

In [3]:
import numpy as np

arr = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [70,80,90],
        [100,110,120]
    ]
])

print(arr.swapaxes(0,1))

[[[ 10  20  30]
  [ 70  80  90]]

 [[ 40  50  60]
  [100 110 120]]]


# 7. squeeze()

In [6]:
arr = np.array([
    [10,20,30,40,50],
    
])
print(arr.shape)

new_arr = arr.squeeze()
print(new_arr)
print(new_arr.shape)

(1, 5)
[10 20 30 40 50]
(5,)


In [ ]:
arr3d = np.array([
    [
        [1,2,3,4]
        
    ],
    [
        [9,10,11,12]
        
    ]
])
# Befor using .squeeze() the shape is
print(arr3d.shape)
# (2, 1, 4)

# After using .squeeze()
new_arr = arr3d.squeeze()
print(new_arr.shape) # (2, 4)
print(new_arr.ndim) # 2


(2, 1, 4)
(2, 4)
2


In [12]:
arr3 = np.array([
    [
        [10],
        [20],
        [30]
    ],
    [
        [40],
        [50],
        [60]
    ]
])
# The Shape of the 3-D befoe using .squeeze()
print(arr3.shape) # (2, 3, 1) 3 different Axis containing 2-Layers, 3-Rows and 1-Column

# After using .squeeze()
new_arr = arr3.squeeze()
print(new_arr.shape) # (2,3)
print(new_arr.ndim) # 2-Dimension

print(new_arr)

(2, 3, 1)
(2, 3)
2
[[10 20 30]
 [40 50 60]]


In [ ]:
arr3D = np.array([
    [
        [10,20,30,40]
        
    ]
])
# The 3-D array has the shape of (1,1,4) 
# Here 2 of these axis has the Size of 1 ie the Layers and the Row So that will be Removed by the .squeeze()
print(arr3D.shape) # (1, 1, 4)

# After using the .squeeze()
new_arr = np.squeeze(arr3D)
print(new_arr.shape)
print(new_arr.ndim) # (4,) because both of the Axis which had the size of 1 is been removed

print(new_arr) # [10 20 30 40]

(1, 1, 4)
(4,)
1
[10 20 30 40]


#### Example on 2-D array

In [ ]:
arr2d = np.array([
    [10,20,30,40],
    
])
# the Shape of this 2-D array is (1,4)
print(arr2d.shape) # (1, 4)

# After using the .squeeze() method
new_arr = arr2d.squeeze()
print(new_arr.shape) # (4,) Axis with the size of 1 is been removed in this case it was the Row

(1, 4)
(4,)


# .expand_dims()

In [ ]:
arr3d = np.array([
    [
        [10,20,30],
        [40,50,60]
    ]
])
print(arr3d.shape)

new_arr = np.expand_dims(arr3d, 0) # Adds another completely new axis of size 1 making it a 4-D array

print(new_arr)
print(new_arr.shape) # (1, 1, 2, 3)
print(new_arr.ndim) # 4

(1, 2, 3)
[[[[10 20 30]
   [40 50 60]]]]
(1, 1, 2, 3)
4


In [ ]:
arr2d = np.array([
    [10,20,30,40],
    [50,60,70,80]
])

# The Shape of this 2-D array is (2,4)
print(arr2d.shape) # (2, 4)
print(arr2d.ndim) # 2

# After using .expand_dims
new_arr = np.expand_dims(arr2d, 0) # Adds a new Axis of size 1 transforming the 2-D array to a 3-D array
print(new_arr)
print(new_arr.shape) # (1, 2, 4) 
print(new_arr.ndim) # 3

(2, 4)
2
[[[10 20 30 40]
  [50 60 70 80]]]
(1, 2, 4)
3


#### Lets add a another Axis

In [ ]:
import numpy as np

arr2d = np.array([
    [10,20,30,40],
    [50,60,70,80]
])
print(arr2d.shape) # (2, 4)


new_arr = np.expand_dims(arr2d, 1) 
print(new_arr)
print(new_arr.shape) # (2, 1, 4) --> 2 Layers (Axis 0) , 1-Rows(Axis 1 ) and 4-Columns (Axis 2)

(2, 4)
[[[10]
  [20]
  [30]
  [40]]

 [[50]
  [60]
  [70]
  [80]]]
(2, 4, 1)
